# Uncomment the next line to define a global platform for your project
# platform :ios, '11.0'

target 'LiveCapturingApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'CocoaMQTT'
# add pods for desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
  pod 'Firebase'
  pod 'Firebase/Database'
  # Pods for LiveCapturingApp

  target 'LiveCapturingAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LiveCapturingAppUITests' do
    # Pods for testing
  end

end
